#!/usr/bin/env bash
#
# Dev container provisioning — runs once, after the container is created.
# Installs no tools: it makes the flake's dev shell the environment of every
# shell, and pays the download cost here rather than in the first terminal.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOADER=/etc/profile.d/10-cdk-devshell.sh

# --- 1. wait for nix-daemon -------------------------------------------------
#
# It is started in the background from the container entrypoint, and postCreate
# beats it; until then nix opens the store directly and dies as non-root.
# Probe by connecting, not by stat'ing the socket: /nix is a named volume, so the
# previous container's socket file survives a rebuild and looks ready.
DAEMON_TIMEOUT=60

daemon_ready() { NIX_REMOTE=daemon nix store info >/dev/null 2>&1; }

wait_for_daemon() {
  for _ in $(seq 1 "${DAEMON_TIMEOUT}"); do
    daemon_ready && return 0
    sleep 1
  done
  return 1
}

if [ -x /nix/var/nix/profiles/default/bin/nix-daemon ]; then
  if ! wait_for_daemon; then
    # The feature's entrypoint already no-ops when a daemon is running.
    echo ">> nix-daemon is not up; starting it"
    sudo -n /usr/local/share/nix-entrypoint.sh true || true
    wait_for_daemon || { echo "!! nix-daemon unreachable; cannot use Nix" >&2; exit 1; }
  fi
  export NIX_REMOTE=daemon
fi

# --- 2. make the mounted cache writable ------------------------------------
#
# A fresh named volume is root-owned, and melange fails mid-build rather than
# falling back when it cannot write its cache.
CACHE_DIR="${HOME}/.cache"
mkdir -p "${CACHE_DIR}" 2>/dev/null || sudo mkdir -p "${CACHE_DIR}"
if [ ! -w "${CACHE_DIR}" ]; then
  echo ">> taking ownership of ${CACHE_DIR}"
  sudo chown "$(id -u):$(id -g)" "${CACHE_DIR}"
fi

# --- 3. put the dev shell in every shell ------------------------------------
#
# Not `exec nix develop` from an rc file: that replaces the shell before it runs
# its command, so `bash -ic '<cmd>'` never runs it, and non-interactive shells get
# no toolchain. print-dev-env re-appends the caller's PATH, keeping docker/sudo.
sudo tee "${LOADER}" >/dev/null <<EOF
# conduktor/container-images: every shell gets the flake's dev shell.
# Generated by .devcontainer/post-create.sh — edit that, not this.
CDK_REPO_ROOT="${REPO_ROOT}"
EOF

# Quoted heredoc: expanded when a shell sources this, not now.
sudo tee -a "${LOADER}" >/dev/null <<'EOF'

# Exported, so subshells skip re-sourcing 90kB per shell.
[ -n "${CDK_DEVSHELL:-}" ] && return 0
# print-dev-env emits bash; a zsh user should run `nix develop` themselves.
[ -n "${ZSH_VERSION:-}" ] && return 0

# Keyed by the flake, so a tool bump regenerates instead of serving the old one.
CDK_ENV_DIR="${HOME}/.cache/cdk-devshell"
CDK_ENV_FILE="${CDK_ENV_DIR}/env-$(cat "${CDK_REPO_ROOT}/flake.nix" \
  "${CDK_REPO_ROOT}/flake.lock" 2>/dev/null | sha256sum | cut -c1-16).sh"

if [ ! -s "${CDK_ENV_FILE}" ]; then
  echo ">> materialising the Nix dev shell (once per flake change)..." >&2
  mkdir -p "${CDK_ENV_DIR}" && rm -f "${CDK_ENV_DIR}"/env-*.sh
  # Re-add print-dev-env's `eval "${shellHook:-}"` guarded: the hook prints a
  # banner, which would land in the output of every non-interactive shell.
  if nix print-dev-env "${CDK_REPO_ROOT}" \
       | grep -vFx 'eval "${shellHook:-}"' > "${CDK_ENV_FILE}.part"; then
    printf '%s\n' 'case $- in *i*) eval "${shellHook:-}" ;; esac' \
      >> "${CDK_ENV_FILE}.part"
    mv "${CDK_ENV_FILE}.part" "${CDK_ENV_FILE}"
  else
    echo "!! could not evaluate the dev shell; run 'nix develop' by hand" >&2
    rm -f "${CDK_ENV_FILE}.part"
  fi
fi

if [ -s "${CDK_ENV_FILE}" ]; then
  . "${CDK_ENV_FILE}"
  export CDK_DEVSHELL=1
fi
EOF
sudo chmod 0644 "${LOADER}"

# /etc/profile.d is read by login shells only; VS Code terminals and
# `docker exec bash` are interactive non-login and read this.
MARKER="conduktor/container-images dev shell"
if ! grep -qF "${MARKER}" "${HOME}/.bashrc" 2>/dev/null; then
  printf '\n# %s\n[ -f %s ] && . %s\n' "${MARKER}" "${LOADER}" "${LOADER}" \
    >>"${HOME}/.bashrc"
fi

# Generates the env file, and with it downloads the whole closure once.
echo ">> materialising the dev shell (first run downloads apko, melange, trivy, ...)"
# shellcheck source=/dev/null
. "${LOADER}"

# --- 4. git hooks -----------------------------------------------------------
#
# A core.hooksPath in the mounted .git/config is a *host* path: git here resolves
# it to something absent and then silently runs no hooks. Point it at the same
# directory via the container's path, with GIT_CONFIG_* — rewriting the shared
# .git/config would change the host's git too.
hooks_path="$(git -C "${REPO_ROOT}" config --get core.hooksPath 2>/dev/null || true)"

install_hooks=true
if [ -n "${hooks_path}" ] && [ -d "${hooks_path}" ]; then
  # Resolves here, so it is a real hook manager rather than a host path.
  echo ">> core.hooksPath is ${hooks_path}; leaving hooks to it"
  install_hooks=false
elif [ -n "${hooks_path}" ]; then
  echo ">> core.hooksPath (${hooks_path}) does not exist here; pointing git at"
  echo "   ${REPO_ROOT}/.git/hooks for shells in this container"
  sudo tee -a "${LOADER}" >/dev/null <<EOF

# Same hooks directory as the host's core.hooksPath, via the container's path.
if [ -z "\${GIT_CONFIG_COUNT:-}" ]; then
  export GIT_CONFIG_COUNT=1
  export GIT_CONFIG_KEY_0=core.hooksPath
  export GIT_CONFIG_VALUE_0="${REPO_ROOT}/.git/hooks"
fi
EOF
fi

# pre-commit refuses while core.hooksPath is set at all, so blank it for this one
# command; it writes .git/hooks/pre-commit, where the override above looks.
if [ "${install_hooks}" = true ]; then
  if ! GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.hooksPath GIT_CONFIG_VALUE_0='' \
       pre-commit install --install-hooks; then
    echo ">> could not install the git hooks; run 'make precommit-run' before pushing"
  fi
fi

cat <<'EOF'

>> Dev container ready. Every shell has the toolchain on PATH — no `nix develop`:
     make help                 # dev targets
     make lint && make test    # what CI runs
     make build IMAGE=debug    # apko build + docker load, via the nested daemon
EOF
